# Generated by Django 2.2.1 on 2019-10-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='author',
            name='user_type',
            field=models.IntegerField(default=1),
        ),
    ]
