# Generated by Django 2.2.1 on 2019-10-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0007_auto_20191006_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='作者名字'),
        ),
    ]
