# Generated by Django 2.2.1 on 2019-10-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0008_auto_20191006_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
