# Generated by Django 2.2.1 on 2019-10-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0009_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default=1, max_length=32, verbose_name='作者名字'),
            preserve_default=False,
        ),
    ]
